pipeline {
    agent {
        docker {
            image 'maven:3.8.6-jdk-11'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/paphuc/eCommerce-Application.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}